src/Entity/Movie.php
<?php

namespace App\Entity;

use App\Repository\MovieRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=MovieRepository::class)
 */
class Movie
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=20, nullable=true)
     */
    private $type;

    /**
     * @ORM\Column(type="string", length=10, nullable=true)
     */
    private $language;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $summary;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $image;

    /**
     * @ORM\Column(type="string", length=10, nullable=true)
     */
    private $genres;

    /**
     * @ORM\Column(type="string", length=20, nullable=true)
     */
    private $country;

    /**
     * @ORM\Column(type="string", length=10, nullable=true)
     */
    private $premiere;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $image_original;

    /**
     * @ORM\Column(type="string", length=3, nullable=true)
     */
    private $length;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(?string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(?string $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function getLanguage(): ?string
    {
        return $this->language;
    }

    public function setLanguage(?string $language): self
    {
        $this->language = $language;

        return $this;
    }

    public function getSummary(): ?string
    {
        return $this->summary;
    }

    public function setSummary(?string $summary): self
    {
        $this->summary = $summary;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getGenres(): ?string
    {
        return $this->genres;
    }

    public function setGenres(?string $genres): self
    {
        $this->genres = $genres;

        return $this;
    }

    public function getCountry(): ?string
    {
        return $this->country;
    }

    public function setCountry(?string $country): self
    {
        $this->country = $country;

        return $this;
    }

    public function getPremiere(): ?string
    {
        return $this->premiere;
    }

    public function setPremiere(?string $premiere): self
    {
        $this->premiere = $premiere;

        return $this;
    }

    public function getImageOriginal(): ?string
    {
        return $this->image_original;
    }

    public function setImageOriginal(?string $image_original): self
    {
        $this->image_original = $image_original;

        return $this;
    }

    public function getLength(): ?string
    {
        return $this->length;
    }

    public function setLength(?string $length): self
    {
        $this->length = $length;

        return $this;
    }
}

src/Form/MovieType.php
<?php

namespace App\Form;

use App\Entity\Movie;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class MovieType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name')
            ->add('type')
            ->add('language')
            ->add('summary')
            ->add('image')
            ->add('genres')
            ->add('country')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Movie::class,
        ]);
    }
}

src/Controller/MovieController.php
<?php

namespace App\Controller;

use App\Entity\Movie;
use App\Form\MovieType;
use App\Repository\MovieRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/")
 */
class MovieController extends AbstractController
{
    //following method renders the home page
    /**
     * @Route("/movie", name="movie_index", methods={"GET"})
     */
    public function index(MovieRepository $movieRepository): Response
    {
        return $this->render('movie/index.html.twig', [
            'movies' => $movieRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="movie_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $movie = new Movie();
        $form = $this->createForm(MovieType::class, $movie);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($movie);
            $entityManager->flush();

            return $this->redirectToRoute('movie_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('movie/new.html.twig', [
            'movie' => $movie,
            'form' => $form,
        ]);
    }

    //Following method renders the movie detail page
    /**
     * @Route("/{name}", name="movie_show", methods={"GET"})
     */
    public function show(Movie $movie): Response
    {
        return $this->render('movie/show.html.twig', [
            'movie' => $movie,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="movie_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Movie $movie): Response
    {
        $form = $this->createForm(MovieType::class, $movie);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('movie_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('movie/edit.html.twig', [
            'movie' => $movie,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="movie_delete", methods={"POST"})
     */
    public function delete(Request $request, Movie $movie): Response
    {
        if ($this->isCsrfTokenValid('delete'.$movie->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($movie);
            $entityManager->flush();
        }

        return $this->redirectToRoute('movie_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0,maximum-scale=1">

        <title>{% block title %}Welcome!{% endblock %}</title>

        {% block stylesheets %}

            <link href="http://fonts.googleapis.com/css?family=Roboto:300,400,700|" rel="stylesheet" type="text/css">
            <link href="{{ asset('assets') }}/fonts/font-awesome.min.css" rel="stylesheet" type="text/css">

            <!-- Loading main css file -->
            <link rel="stylesheet" href="{{ asset('assets') }}/style.css">

        {% endblock %}

        {% block javascripts %}

            <script src="{{ asset('assets') }}/js/ie-support/html5.js"></script>
            <script src="{{ asset('assets') }}/js/ie-support/respond.js"></script>

        {% endblock %}
    </head>
    <body>
    <div id="site-content">
        <header class="site-header">
            <div class="container">
                <a href="{{ path('movie_index') }}" id="branding">
                    <img src="{{ asset('assets') }}/images/logo.png" alt="" class="logo">
                    <div class="logo-copy">
                        <h1 class="site-title">Bircom Movies</h1>
                        <small class="site-description">Our Comedy Movies</small>
                    </div>
                </a> <!-- #branding -->

                <div class="main-navigation">
                    <button type="button" class="menu-toggle"><i class="fa fa-bars"></i></button>
                    <ul class="menu">
                        <li class="menu-item current-menu-item">
                            <a href="{{ path('movie_index') }}">Home</a>
                        </li>
                    </ul> <!-- .menu -->
                </div> <!-- .main-navigation -->
                <div class="mobile-navigation"></div>
            </div>
        </header>
        {% block body %}{% endblock %}

        {% block footer %}
            <footer class="site-footer">
                <div class="container">
                    <div class="colophon">Copyright 2021 Bircom Telekomünikasyon ve Bilişim Hizmetleri,
                        Designed by Mustafa Kemal KURUDAĞ. All rights reserved</div>
                </div> <!-- .container -->
            </footer>
        {% endblock %}
    </div>
        <script src="{{ asset('assets') }}/js/jquery-1.11.1.min.js"></script>
        <script src="{{ asset('assets') }}/js/plugins.js"></script>
        <script src="{{ asset('assets') }}/js/app.js"></script>

    </body>
</html>

templates/movie/_delete_form.html.twig
<form method="post" action="{{ path('movie_delete', {'id': movie.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ movie.id) }}">
    <button class="btn">Delete</button>
</form>

templates/movie/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/movie/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Movie{% endblock %}

{% block body %}
    <h1>Edit Movie</h1>

    {{ include('movie/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('movie_index') }}">back to list</a>

    {{ include('movie/_delete_form.html.twig') }}
{% endblock %}

templates/movie/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Movie index{% endblock %}

{% block body %}

    <main class="main-content">
        <div class="container">
            <div class="page">
                <div class="breadcrumbs">
                    <a href="{{ path('movie_index') }}">Home</a>
                </div>

                <div class="movie-list">

                    {% if movies is empty %}
                        <p>
                            The database is empty. If you want to see the movies,
                            you need to go to the project folder at the command prompt(cmd)
                            and run the <b>php bin\console fetch-movies</b> command. </p>
                        <p>
                            Veritabanı boş. Eğer filmleri görmek isterseniz komut isteminde(cmd) proje klasörüne gelerek
                            <b>php bin\console fetch-movies</b> komutunu çalıştırmanız gerekmektedir.
                        </p>
                    {% else %}

                    {% for movie in movies %}
                    <div class="movie">
                        <figure class="movie-poster">
                            <img src="{{ movie.image }}" alt="#">
                        </figure>
                        <div class="movie-title">
                            <a href="{{ path('movie_show', {'name':movie.name} ) }}">{{ movie.name }}</a>
                        </div>
                        <p>{{ movie.summary | u.truncate(70) | raw }}...</p>
                    </div>
                    {% endfor %}
                    {% endif %}
                </div> <!-- .movie-list -->

            </div>
        </div> <!-- .container -->
    </main>
</div>
    <!-- Default snippet for navigation -->
{% endblock %}

templates/movie/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Movie{% endblock %}

{% block body %}
    <h1>Create new Movie</h1>

    {{ include('movie/_form.html.twig') }}

    <a href="{{ path('movie_index') }}">back to list</a>
{% endblock %}

templates/movie/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ movie.name }}{% endblock %}

{% block body %}
    <main class="main-content">
        <div class="container">
            <div class="page">
                <div class="breadcrumbs">
                    <a href="{{ path('movie_index') }}">Home</a>
                    <span>{{ movie.name }}</span>
                </div>
                <div class="content">
                    <div class="row">
                        <div class="col-md-6">
                            <figure class="movie-poster"><img src="{{ movie.imageOriginal }}" alt="#"></figure>
                        </div>
                        <div class="col-md-6">
                            <h2 class="movie-title">{{ movie.name }}</h2>
                            <div class="movie-summary">
                                <p>
                                    {{ movie.summary|raw }}
                                </p>
                            </div>
                            <ul class="movie-meta">
                                <li><strong>Length:</strong> {{ movie.length }} min</li>
                                <li><strong>Premiere:</strong> {{ movie.premiere }} ({{ movie.country }})</li>
                                <li><strong>Category:</strong> {{ movie.type }}</li>
                                <li><strong>Language:</strong> {{ movie.language }}</li>
                            </ul>
                        </div>
                    </div> <!-- .row -->
                </div>
            </div>
        </div> <!-- .container -->
    </main>
{% endblock %}